[package]
name = "weave-api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
argon2 = "0.6.0"
axum = "0.8.9"
base64 = "0.23.1"
chrono = { version = "0.4.45", features = ["serde"] }
chrono-tz = "0.10.4"
dotenvy = "0.15.7"
hex = "0.4.3"
hmac = "0.13.0"
jsonwebtoken = { version = "11.0.0", features = ["rust_crypto"] }
password-hash = { version = "0.6.1", features = ["phc", "alloc", "getrandom"] }
rand = "0.10.2"
redis = { version = "1.7.0", features = ["tokio-comp", "tokio-rustls-comp", "connection-manager"] }
sea-orm = { version = "2.0.2", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "sqlx-sqlite"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
subtle = "2.6.1"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.1", features = ["fs", "cors", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["json", "env-filter"] }
