//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    #[sea_orm(column_name = "emailHash", column_type = "Text", unique)]
    pub email_hash: String,
    #[sea_orm(column_type = "Text", unique)]
    pub handle: String,
    #[sea_orm(column_name = "displayName", column_type = "Text")]
    pub display_name: String,
    #[sea_orm(column_name = "birthDate")]
    pub birth_date: DateTime,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub timezone: String,
    #[sea_orm(column_type = "Text")]
    pub locale: String,
    pub verified: bool,
    #[sea_orm(column_name = "lastSeenAt")]
    pub last_seen_at: Option<DateTime>,
    #[sea_orm(column_name = "deletionRequestedAt")]
    pub deletion_requested_at: Option<DateTime>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audit_events::Entity")]
    AuditEvents,
    #[sea_orm(has_many = "super::consent_records::Entity")]
    ConsentRecords,
    #[sea_orm(has_many = "super::credit_balances::Entity")]
    CreditBalances,
    #[sea_orm(has_many = "super::devices::Entity")]
    Devices,
    #[sea_orm(has_many = "super::join_requests::Entity")]
    JoinRequests,
    #[sea_orm(has_many = "super::live_activity_sessions::Entity")]
    LiveActivitySessions,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
    #[sea_orm(has_many = "super::plans::Entity")]
    Plans,
    #[sea_orm(has_one = "super::preferences::Entity")]
    Preferences,
    #[sea_orm(has_one = "super::profiles::Entity")]
    Profiles,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
    #[sea_orm(has_one = "super::subscriptions::Entity")]
    Subscriptions,
    #[sea_orm(has_many = "super::unit_purchases::Entity")]
    UnitPurchases,
}

impl Related<super::audit_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditEvents.def()
    }
}

impl Related<super::consent_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConsentRecords.def()
    }
}

impl Related<super::credit_balances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CreditBalances.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::join_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JoinRequests.def()
    }
}

impl Related<super::live_activity_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LiveActivitySessions.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::plans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plans.def()
    }
}

impl Related<super::preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Preferences.def()
    }
}

impl Related<super::profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profiles.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscriptions.def()
    }
}

impl Related<super::unit_purchases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UnitPurchases.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
