//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "conversations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "planId", column_type = "Text")]
    pub plan_id: String,
    #[sea_orm(column_name = "requestId", column_type = "Text", unique)]
    pub request_id: String,
    #[sea_orm(column_name = "hostId", column_type = "Text")]
    pub host_id: String,
    #[sea_orm(column_name = "guestId", column_type = "Text")]
    pub guest_id: String,
    #[sea_orm(column_name = "openedAt")]
    pub opened_at: DateTime,
    #[sea_orm(column_name = "lastMessageAt")]
    pub last_message_at: Option<DateTime>,
    #[sea_orm(column_name = "closedAt")]
    pub closed_at: Option<DateTime>,
    #[sea_orm(column_name = "closedBy", column_type = "Text", nullable)]
    pub closed_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::GuestId",
        to = "super::accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Accounts2,
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::HostId",
        to = "super::accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Accounts1,
    #[sea_orm(
        belongs_to = "super::join_requests::Entity",
        from = "Column::RequestId",
        to = "super::join_requests::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    JoinRequests,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
    #[sea_orm(
        belongs_to = "super::plans::Entity",
        from = "Column::PlanId",
        to = "super::plans::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Plans,
}

impl Related<super::join_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JoinRequests.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::plans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plans.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
