//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "devices")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(
        column_name = "accountId",
        column_type = "Text",
        unique_key = "devices_accountId_vendorId_key"
    )]
    pub account_id: String,
    #[sea_orm(column_type = "Text")]
    pub platform: String,
    #[sea_orm(
        column_name = "vendorId",
        column_type = "Text",
        unique_key = "devices_accountId_vendorId_key"
    )]
    pub vendor_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub model: Option<String>,
    #[sea_orm(column_name = "osVersion", column_type = "Text", nullable)]
    pub os_version: Option<String>,
    #[sea_orm(column_name = "appVersion", column_type = "Text", nullable)]
    pub app_version: Option<String>,
    #[sea_orm(column_name = "apnsToken", column_type = "Text", nullable)]
    pub apns_token: Option<String>,
    #[sea_orm(column_name = "pushToStartToken", column_type = "Text", nullable)]
    pub push_to_start_token: Option<String>,
    #[sea_orm(column_name = "apnsEnvironment", column_type = "Text")]
    pub apns_environment: String,
    #[sea_orm(column_name = "lastSeenAt")]
    pub last_seen_at: DateTime,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(has_many = "super::live_activity_sessions::Entity")]
    LiveActivitySessions,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::live_activity_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LiveActivitySessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
