//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "plans")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "authorId", column_type = "Text")]
    pub author_id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub note: String,
    #[sea_orm(column_type = "Text")]
    pub category: String,
    #[sea_orm(column_name = "startsAt")]
    pub starts_at: DateTime,
    #[sea_orm(column_type = "Text")]
    pub city: String,
    #[sea_orm(column_name = "latRounded", column_type = "Double")]
    pub lat_rounded: f64,
    #[sea_orm(column_name = "lonRounded", column_type = "Double")]
    pub lon_rounded: f64,
    pub capacity: i32,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_name = "cancelledAt")]
    pub cancelled_at: Option<DateTime>,
    /// L'heure à laquelle le rappel est parti. Nul tant qu'il n'est pas parti.
    #[sea_orm(column_name = "remindedAt")]
    pub reminded_at: Option<DateTime>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AuthorId",
        to = "super::accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(has_many = "super::conversations::Entity")]
    Conversations,
    #[sea_orm(has_many = "super::join_requests::Entity")]
    JoinRequests,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl Related<super::join_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JoinRequests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
