//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "preferences")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "accountId", column_type = "Text", unique)]
    pub account_id: String,
    #[sea_orm(column_name = "minAge")]
    pub min_age: i32,
    #[sea_orm(column_name = "maxAge")]
    pub max_age: i32,
    #[sea_orm(column_name = "maxDistanceKm")]
    pub max_distance_km: i32,
    #[sea_orm(column_name = "seekingJson", column_type = "Text")]
    pub seeking_json: String,
    #[sea_orm(column_name = "categoriesJson", column_type = "Text")]
    pub categories_json: String,
    #[sea_orm(column_name = "escaleCity", column_type = "Text", nullable)]
    pub escale_city: Option<String>,
    #[sea_orm(column_name = "escaleUntil")]
    pub escale_until: Option<DateTime>,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Accounts,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
