//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "accountId", column_type = "Text", unique)]
    pub account_id: String,
    #[sea_orm(column_type = "Text")]
    pub city: String,
    #[sea_orm(column_name = "latRounded", column_type = "Double")]
    pub lat_rounded: f64,
    #[sea_orm(column_name = "lonRounded", column_type = "Double")]
    pub lon_rounded: f64,
    #[sea_orm(column_type = "Text")]
    pub gender: String,
    #[sea_orm(column_type = "Text")]
    pub bio: String,
    #[sea_orm(column_name = "photoKey", column_type = "Text", nullable)]
    pub photo_key: Option<String>,
    #[sea_orm(column_name = "photoReviewedAt")]
    pub photo_reviewed_at: Option<DateTime>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Accounts,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
