//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "subscriptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "accountId", column_type = "Text", unique)]
    pub account_id: String,
    #[sea_orm(column_type = "Text")]
    pub tier: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub period: Option<String>,
    #[sea_orm(column_name = "storeKitProductId", column_type = "Text", nullable)]
    pub store_kit_product_id: Option<String>,
    #[sea_orm(
        column_name = "originalTransactionId",
        column_type = "Text",
        nullable,
        unique
    )]
    pub original_transaction_id: Option<String>,
    #[sea_orm(column_name = "renewsAt")]
    pub renews_at: Option<DateTime>,
    #[sea_orm(column_name = "expiresAt")]
    pub expires_at: Option<DateTime>,
    #[sea_orm(column_name = "inGracePeriod")]
    pub in_grace_period: bool,
    #[sea_orm(column_name = "cancelledAt")]
    pub cancelled_at: Option<DateTime>,
    #[sea_orm(column_type = "Text")]
    pub environment: String,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Accounts,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
