//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "unit_purchases")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "accountId", column_type = "Text")]
    pub account_id: String,
    #[sea_orm(column_type = "Text")]
    pub sku: String,
    #[sea_orm(column_name = "transactionId", column_type = "Text", unique)]
    pub transaction_id: String,
    pub quantity: i32,
    #[sea_orm(column_name = "priceCents")]
    pub price_cents: i32,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    #[sea_orm(column_type = "Text")]
    pub environment: String,
    #[sea_orm(column_name = "consumedAt")]
    pub consumed_at: Option<DateTime>,
    #[sea_orm(column_name = "refundedAt")]
    pub refunded_at: Option<DateTime>,
    #[sea_orm(column_name = "purchasedAt")]
    pub purchased_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Accounts,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
